<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Velaris.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Hosts\Velaris.SmtpSubmission.Host\Velaris.SmtpSubmission.Host.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Submission\Velaris.Submission.Domain\Velaris.Submission.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Submission\Velaris.Submission.Application\Velaris.Submission.Application.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Submission\Velaris.Submission.Infrastructure\Velaris.Submission.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\src\Modules\Submission\Velaris.Submission.Smtp\Velaris.Submission.Smtp.csproj" />
  </ItemGroup>

</Project>
