<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Velaris.Submission.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Velaris.Submission.Application\Velaris.Submission.Application.csproj" />
    <ProjectReference Include="..\Velaris.Submission.Domain\Velaris.Submission.Domain.csproj" />
  </ItemGroup>

</Project>
