// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Velaris.Submission.Infrastructure.Persistence;

#nullable disable

namespace Velaris.Submission.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubmissionDbContext))]
    partial class SubmissionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("submission")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.AttachmentReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpaqueObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "OrderIndex");

                    b.ToTable("attachment_references", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("credentials", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.CredentialVerifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("IterationCount")
                        .HasColumnType("integer");

                    b.Property<string>("Mechanism")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ServerKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("StoredKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId", "Version")
                        .IsUnique();

                    b.ToTable("credential_verifiers", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("MessageId", "RecipientEmail")
                        .IsUnique();

                    b.ToTable("deliveries", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.EnvironmentQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AllocatedLimit")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("UsedCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "PeriodType", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("environment_quotas", "submission", t =>
                        {
                            t.HasCheckConstraint("CK_environment_quotas_allocated_limit", "\"AllocatedLimit\" >= 0");

                            t.HasCheckConstraint("CK_environment_quotas_used_count", "\"UsedCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthenticatedUser")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ClientEhlo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvelopeSender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<string>("SubmissionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TlsCipher")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("TenantId", "AcceptedAtUtc");

                    b.ToTable("messages", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.MessageBodyPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Charset")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentDisposition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContentTransferEncoding")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "OrderIndex");

                    b.ToTable("message_body_parts", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.MessageHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "OrderIndex");

                    b.ToTable("message_headers", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.SenderGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId", "Type", "Value")
                        .IsUnique();

                    b.ToTable("sender_grants", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Suppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EnhancedStatusCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("SmtpCode")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Email")
                        .IsUnique();

                    b.ToTable("suppressions", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MaxMessageSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxRecipientsPerSubmission")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSmtpSessionDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", "submission", t =>
                        {
                            t.HasCheckConstraint("CK_tenants_max_duration", "\"MaxSmtpSessionDurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_tenants_max_message_size", "\"MaxMessageSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_tenants_max_recipients", "\"MaxRecipientsPerSubmission\" > 0");
                        });
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.TenantEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("environments", "submission");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.TenantQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AllocatedLimit")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("UsedCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PeriodType", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("tenant_quotas", "submission", t =>
                        {
                            t.HasCheckConstraint("CK_tenant_quotas_allocated_limit", "\"AllocatedLimit\" >= 0");

                            t.HasCheckConstraint("CK_tenant_quotas_used_count", "\"UsedCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.AttachmentReference", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Message", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Credential", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.TenantEnvironment", "Environment")
                        .WithMany("Credentials")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Velaris.Submission.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Credentials")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.CredentialVerifier", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Credential", "Credential")
                        .WithMany("Verifiers")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Delivery", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.TenantEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Velaris.Submission.Domain.Entities.Message", "Message")
                        .WithMany("Deliveries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Velaris.Submission.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("Message");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.EnvironmentQuota", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.TenantEnvironment", "Environment")
                        .WithMany("Quotas")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Message", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Velaris.Submission.Domain.Entities.TenantEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Velaris.Submission.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Messages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credential");

                    b.Navigation("Environment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.MessageBodyPart", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Message", "Message")
                        .WithMany("BodyParts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.MessageHeader", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Message", "Message")
                        .WithMany("Headers")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.SenderGrant", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Credential", "Credential")
                        .WithMany("SenderGrants")
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Suppression", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.TenantEnvironment", "Environment")
                        .WithMany("Suppressions")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.TenantEnvironment", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Environments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.TenantQuota", b =>
                {
                    b.HasOne("Velaris.Submission.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Quotas")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Credential", b =>
                {
                    b.Navigation("SenderGrants");

                    b.Navigation("Verifiers");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Message", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BodyParts");

                    b.Navigation("Deliveries");

                    b.Navigation("Headers");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Environments");

                    b.Navigation("Messages");

                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("Velaris.Submission.Domain.Entities.TenantEnvironment", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Quotas");

                    b.Navigation("Suppressions");
                });
#pragma warning restore 612, 618
        }
    }
}
